name: Deploy to Test Server

on:
  push:
    branches:
      - dev1
      - main

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Show Current User
        run: whoami

      - name: Show Working Directory
        run: pwd

      - name: List Repository Files
        run: ls -la

      - name: Copy Files to Apache
        run: |
          rsync -av --delete \
          $GITHUB_WORKSPACE/ \
          /opt/lampp/htdocs/msdpl.com_new/

      - name: Verify Deployment
        run: |
          ls -la /opt/lampp/htdocs/msdpl.com_new